export interface Product {
  id: string;
  name: string;
  price: number;
  category: string;
  images: string[];
  sizes: string[];
  colors: string[];
  description: string;
  collection?: string;
}

export const products: Product[] = [
  // -------------------------------
  // 🧵 SAMARRETES
  // -------------------------------
  {
    id: "ts001",
    name: "Samarreta clàssica Lacoste blanc",
    price: 65,
    category: "samarretes",
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=600&fit=crop", "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&h=600&fit=crop"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["blanc"],
    description: "Samarreta de cotó orgànic amb logotip Lacoste brodat.",
  },
  {
    id: "ts002",
    name: "Samarreta verda cocodril",
    price: 69,
    category: "samarretes",
    images: ["https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&h=600&fit=crop", "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=600&fit=crop"],
    sizes: ["M", "L", "XL"],
    colors: ["verd"],
    description: "Disseny icònic amb el verd corporatiu Lacoste.",
  },
  {
    id: "ts003",
    name: "Samarreta negra premium",
    price: 75,
    category: "samarretes",
    images: ["https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=600&h=600&fit=crop"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["negre"],
    description: "Teixit premium respirable amb acabat esportiu.",
  },
  {
    id: "ts004",
    name: "Polo blanc clàssic Lacoste",
    price: 95,
    category: "samarretes",
    images: ["https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&h=600&fit=crop", "https://images.unsplash.com/photo-1598032895397-b9132f8b5be5?w=600&h=600&fit=crop"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["blanc"],
    description: "El polo més icònic de Lacoste en versió tradicional.",
  },
  {
    id: "ts005",
    name: "Polo blau marí",
    price: 99,
    category: "samarretes",
    images: ["https://images.unsplash.com/photo-1598032895397-b9132f8b5be5?w=600&h=600&fit=crop"],
    sizes: ["S", "M", "L"],
    colors: ["blau marí"],
    description: "Polo versàtil inspirat en la línia esportiva francesa.",
  },

  // -------------------------------
  // 👖 PANTALONS
  // -------------------------------
  {
    id: "pt001",
    name: "Pantalons xandall Lacoste gris",
    price: 89,
    category: "pantalons",
    images: ["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&h=600&fit=crop"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["gris"],
    description: "Xandall còmode amb goma elàstica i logo lateral.",
  },
  {
    id: "pt002",
    name: "Pantalons xandall verd",
    price: 92,
    category: "pantalons",
    images: ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&h=600&fit=crop"],
    sizes: ["M", "L"],
    colors: ["verd"],
    description: "Model ajustat ideal per a entrenaments intensos.",
  },
  {
    id: "pt003",
    name: "Short esportiu blanc",
    price: 55,
    category: "pantalons",
    images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600&h=600&fit=crop"],
    sizes: ["S", "M", "L"],
    colors: ["blanc"],
    description: "Short lleuger per a running i tennis.",
  },
  {
    id: "pt004",
    name: "Pantalons tècnics negres",
    price: 110,
    category: "pantalons",
    images: ["https://images.unsplash.com/photo-1602293589930-45aad59ba3ab?w=600&h=600&fit=crop"],
    sizes: ["M", "L", "XL"],
    colors: ["negre"],
    description: "Material tècnic d'alt rendiment anti-humitat.",
  },
  {
    id: "pt005",
    name: "Pantalons cotó premium",
    price: 99,
    category: "pantalons",
    images: ["https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&h=600&fit=crop"],
    sizes: ["S", "M", "L"],
    colors: ["blau marí"],
    description: "Cotó d'alta qualitat amb tall modern.",
  },

  // -------------------------------
  // 🧥 JAQUETES
  // -------------------------------
  {
    id: "jk001",
    name: "Jaqueta coupe-vent blanca",
    price: 130,
    category: "jaquetes",
    images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=600&fit=crop"],
    sizes: ["S", "M", "L"],
    colors: ["blanc"],
    description: "Ultra lleugera amb protecció contra el vent.",
  },
  {
    id: "jk002",
    name: "Jaqueta tèrmica verda",
    price: 160,
    category: "jaquetes",
    images: ["https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&h=600&fit=crop"],
    sizes: ["M", "L", "XL"],
    colors: ["verd"],
    description: "Tecnologia calor tèrmic per clima fred.",
  },
  {
    id: "jk003",
    name: "Jaqueta plomes premium",
    price: 220,
    category: "jaquetes",
    images: ["https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600&h=600&fit=crop"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["negre"],
    description: "Plomes lleugeres amb resistència a l'aigua.",
  },
  {
    id: "jk004",
    name: "Jaqueta esportiva Djokovic",
    price: 180,
    category: "jaquetes",
    images: ["https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=600&fit=crop"],
    sizes: ["M", "L", "XL"],
    colors: ["blanc", "verd"],
    description: "Disseny oficial Djokovic 2025.",
    collection: "djokovic",
  },
  {
    id: "jk005",
    name: "Jaqueta Nadal x Lacoste",
    price: 185,
    category: "jaquetes",
    images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=600&fit=crop"],
    sizes: ["M", "L"],
    colors: ["blau", "groc"],
    description: "Col·lecció exclusiva Rafa Nadal 2025.",
    collection: "nadal",
  },

  // -------------------------------
  // 👟 VAMBES
  // -------------------------------
  {
    id: "sh001",
    name: "Vambes blanques clàssiques",
    price: 120,
    category: "calcat",
    images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&h=600&fit=crop"],
    sizes: ["40", "41", "42", "43", "44"],
    colors: ["blanc"],
    description: "Disseny minimalista amb sola premium.",
  },
  {
    id: "sh002",
    name: "Vambes negres estil esportiu",
    price: 125,
    category: "calcat",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop"],
    sizes: ["41", "42", "43"],
    colors: ["negre"],
    description: "Inspiració running d'alt rendiment.",
  },
  {
    id: "sh003",
    name: "Vambes Djokovic Pro 2025",
    price: 150,
    category: "calcat",
    images: ["https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&h=600&fit=crop"],
    sizes: ["41", "42", "43", "44"],
    colors: ["blanc", "vermell"],
    description: "Model oficial Djokovic 2025.",
    collection: "djokovic",
  },
  {
    id: "sh004",
    name: "Vambes Nadal Terra Batuda",
    price: 155,
    category: "calcat",
    images: ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&h=600&fit=crop"],
    sizes: ["40", "41", "42", "43"],
    colors: ["taronja", "blau"],
    description: "Model inspirat en Roland Garros.",
    collection: "nadal",
  },
  {
    id: "sh005",
    name: "Sneakers verd Lacoste",
    price: 130,
    category: "calcat",
    images: ["https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&h=600&fit=crop"],
    sizes: ["41", "42", "43", "44"],
    colors: ["verd"],
    description: "Estètica moderna amb detalls minimalistes.",
  },

  // -------------------------------
  // 🎒 ACCESSORIS
  // -------------------------------
  {
    id: "ac001",
    name: "Gorra blanca Lacoste",
    price: 35,
    category: "accessoris",
    images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&h=600&fit=crop"],
    sizes: ["uni"],
    colors: ["blanc"],
    description: "Gorra ajustable lleugera.",
  },
  {
    id: "ac002",
    name: "Bossa esportiva verda",
    price: 60,
    category: "accessoris",
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop"],
    sizes: ["uni"],
    colors: ["verd"],
    description: "Ideal per a gimnàs o entrenaments.",
  },
  {
    id: "ac003",
    name: "Motxilla Lacoste negra",
    price: 75,
    category: "accessoris",
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop"],
    sizes: ["uni"],
    colors: ["negre"],
    description: "Motxilla urbana resistent.",
  },
  {
    id: "ac004",
    name: "Cinturó tèxtil blau",
    price: 40,
    category: "accessoris",
    images: ["https://images.unsplash.com/photo-1624222247344-550fb60583c8?w=600&h=600&fit=crop"],
    sizes: ["uni"],
    colors: ["blau marí"],
    description: "Ajustable amb sivella metàl·lica.",
  },
  {
    id: "ac005",
    name: "Bandolera Djokovic",
    price: 85,
    category: "accessoris",
    images: ["https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&h=600&fit=crop"],
    sizes: ["uni"],
    colors: ["blanc", "verd"],
    description: "Accessor oficial Djokovic.",
    collection: "djokovic",
  },
  
  // Productes addicionals per arribar a 35
  {
    id: "ts006",
    name: "Samarreta tècnica running",
    price: 79,
    category: "samarretes",
    images: ["https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&h=600&fit=crop"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["negre", "gris"],
    description: "Material transpirable d'alta tecnologia.",
  },
  {
    id: "ts007",
    name: "Polo Djokovic edició limitada",
    price: 125,
    category: "samarretes",
    images: ["https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&h=600&fit=crop"],
    sizes: ["M", "L", "XL"],
    colors: ["blanc", "verd"],
    description: "Edició especial signatura Djokovic.",
    collection: "djokovic",
  },
  {
    id: "ts008",
    name: "Polo Nadal Roland Garros",
    price: 129,
    category: "samarretes",
    images: ["https://images.unsplash.com/photo-1598032895397-b9132f8b5be5?w=600&h=600&fit=crop"],
    sizes: ["S", "M", "L"],
    colors: ["blau", "taronja"],
    description: "Commemoratiu victories Roland Garros.",
    collection: "nadal",
  },
  {
    id: "pt006",
    name: "Shorts Djokovic Pro",
    price: 75,
    category: "pantalons",
    images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600&h=600&fit=crop"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["blanc", "verd"],
    description: "Shorts oficials col·lecció Djokovic.",
    collection: "djokovic",
  },
  {
    id: "pt007",
    name: "Pantalons entrenament Nadal",
    price: 95,
    category: "pantalons",
    images: ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&h=600&fit=crop"],
    sizes: ["M", "L", "XL"],
    colors: ["blau", "groc"],
    description: "Pantalons d'entrenament Rafa Nadal.",
    collection: "nadal",
  },
  {
    id: "jk006",
    name: "Jaqueta impermeabilitzada",
    price: 145,
    category: "jaquetes",
    images: ["https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=600&fit=crop"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["negre", "gris"],
    description: "Protecció total contra pluja i vent.",
  },
  {
    id: "jk007",
    name: "Jaqueta sport elegance",
    price: 175,
    category: "jaquetes",
    images: ["https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&h=600&fit=crop"],
    sizes: ["M", "L", "XL"],
    colors: ["blanc", "blau"],
    description: "Elegància esportiva per qualsevol ocasió.",
  },
  {
    id: "sh006",
    name: "Vambes urbanes premium",
    price: 140,
    category: "calcat",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop"],
    sizes: ["40", "41", "42", "43", "44"],
    colors: ["blanc", "negre"],
    description: "Confort urbà amb estil esportiu.",
  },
  {
    id: "sh007",
    name: "Sandàlies Lacoste slide",
    price: 45,
    category: "calcat",
    images: ["https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600&h=600&fit=crop"],
    sizes: ["40", "41", "42", "43"],
    colors: ["blanc", "verd"],
    description: "Sandàlies còmodes per l'estiu.",
  },
  {
    id: "ac006",
    name: "Mitjons pack 3 parells",
    price: 25,
    category: "accessoris",
    images: ["https://images.unsplash.com/photo-1586351012965-861624544334?w=600&h=600&fit=crop"],
    sizes: ["uni"],
    colors: ["blanc", "negre", "verd"],
    description: "Pack 3 parells cotó premium.",
  },
  {
    id: "ac007",
    name: "Bossa esportiva gran",
    price: 95,
    category: "accessoris",
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop"],
    sizes: ["uni"],
    colors: ["negre"],
    description: "Capacitat XL per viatges.",
  },
];
